### ISSUE TITLE
Received spam about pdnsadmin

### ISSUE THREAD

**Issue by cmouse** [pdnsadmin/pdnsadmin#1]
You have sent unsolicited spam to my email. Please fix your email list to not send spam without opt-in. Thank you.

Sample of spam:

PDNSADMIN (http://pdnsadmin.us15.list-manage.com/track/click?u=08d5226573bff736304f4d73f&id=f73f521675&e=b9f6440208)

Hi Aki Tuomi

You are looking for a tool to manage your PowerDNS instead of using command line?
pdnsAdmin (http://pdnsadmin.us15.list-manage.com/track/click?u=08d5226573bff736304f4d73f&id=1ef3bdd5e9&e=b9f6440208) is a right webapp with supporting multi DNS record types and connect PowerDNS server purely via its API so it's not
matter whatever your PowerDNS DB is.
Demo: http://pdnsadmin.us15.list-manage.com/track/click?u=08d5226573bff736304f4d73f&id=cd569cf0af&e=b9f6440208
user: demo@pdnsadmin.com / password: admindemo
Docs: http://pdnsadmin.us15.list-manage.com/track/click?u=08d5226573bff736304f4d73f&id=9f571873a7&e=b9f6440208
Github: http://pdnsadmin.us15.list-manage.com/track/click?u=08d5226573bff736304f4d73f&id=8bb4df5f4d&e=b9f6440208

pdnsAdmin
pdnsAdmin
pdnsAdmin

pdnsAdmin Features
pdnsAdmin Features:
- An Opensource project
- Working with PowerDNS through its API
- Allow Sync existed domain names from PowerDNS server to pdnsAdmin
- Manage User privileges with specify roles
- Log all the actions so easy to keep tracking the changes on DNS
- Fully support docker images, docker-compose

pdnsAdmin
pdnsAdmin
pdnsAdmin
Contribution
Contribution:
You are invited to contribute new features, fixes, or updates, large or small; we are always thrilled to receive pull requests, and do our best to process them as fast as we can.

pdnsAdmin   pdnsAdmin
www.pdnsAdmin (http://pdnsadmin.us15.list-manage1.com/track/click?u=08d5226573bff736304f4d73f&id=08b727a028&e=b9f6440208) | Demo (http://pdnsadmin.us15.list-manage2.com/track/click?u=08d5226573bff736304f4d73f&id=9916f15f67&e=b9f6440208)
| Github (http://pdnsadmin.us15.list-manage.com/track/click?u=08d5226573bff736304f4d73f&id=5ab1e2a18c&e=b9f6440208)
pdnsAdmin

============================================================

This email was sent to cmouse@cmouse.fi (mailto:cmouse@cmouse.fi)
why did I get this? (http://pdnsadmin.us15.list-manage.com/about?u=08d5226573bff736304f4d73f&id=fc89fc47b6&e=b9f6440208&c=1165ed665f)     unsubscribe from this list
(http://pdnsadmin.us15.list-manage.com/unsubscribe?u=08d5226573bff736304f4d73f&id=fc89fc47b6&e=b9f6440208&c=1165ed665f)     update subscription preferences
(http://pdnsadmin.us15.list-manage.com/profile?u=08d5226573bff736304f4d73f&id=fc89fc47b6&e=b9f6440208)
pdnsAdmin Team . 171 Cao Thang St . District 10, Ho Chi Minh city 75000 . Vietnam

**Comment by sporkman** [comment]
Very weird to me is not only are they openly spamming the PDNS list, but there is no mention of who the developer(s) are on the website.  Seems shady.
